version: "3.9"

services:
  fastapi_base:
    build:
      context: .
      dockerfile: .docker/Dockerfile
    restart: always
    hostname: fastapi_RegistroWeb
    container_name: fastapi_RegistroWeb
    ports:
      - "8020:8020"
    volumes:
      - .:/opt/alloxentric
    env_file:
      - env/app.env
      - env/keycloak.env
      - env/mongo.env
    healthcheck:
      test: curl --fail http://localhost:8020/health || exit 1
      interval: 60s
      retries: 5
      start_period: 20s
      timeout: 2s

networks:
  default:
    name: alloxentric.com